- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: Enable and start docker
      service:
        name: docker
        enabled: yes
        state: started
